// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANrNRAwkJmqXQr64vTa2is8fsUmPdaV68',
    appId: '1:878744335468:web:cae372465a90ef1ffc1449',
    messagingSenderId: '878744335468',
    projectId: 'brew-crew-flutter-c5ddc',
    authDomain: 'brew-crew-flutter-c5ddc.firebaseapp.com',
    storageBucket: 'brew-crew-flutter-c5ddc.appspot.com',
    measurementId: 'G-9ZXFZEBK1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe-kNPmXmlY35yWdeJs6biwL95ul-dXlE',
    appId: '1:878744335468:android:7abe0f2798a200f6fc1449',
    messagingSenderId: '878744335468',
    projectId: 'brew-crew-flutter-c5ddc',
    storageBucket: 'brew-crew-flutter-c5ddc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIcp7t7cFtZCHMAAuVypFbMvxZwkxC-7A',
    appId: '1:878744335468:ios:756d4ca5747b2cc9fc1449',
    messagingSenderId: '878744335468',
    projectId: 'brew-crew-flutter-c5ddc',
    storageBucket: 'brew-crew-flutter-c5ddc.appspot.com',
    iosClientId: '878744335468-lgtguuha8mn4971d7e320td2844j8401.apps.googleusercontent.com',
    iosBundleId: 'y',
  );
}
